name: Deploy Frontend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'front_end_voltage/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: front_end_voltage
        run: npm install

      - name: Build project
        working-directory: front_end_voltage
        run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: front-end-volt-eddnd6fpg9gtf0fj
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: front_end_voltage/build
